name: Java CI project

on: [push]
permissions:
    contents: 'read'
    issues: 'read'
    pull-requests: 'write'
    checks: 'write'
jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 21 ]
    name: Java ${{ matrix.java }} compile
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-package: jdk
          java-version: ${{ matrix.java }}

      - name: Compile
        run: mvn -f ./Test/pom.xml -B compile

  build:
    runs-on: ubuntu-latest
    needs: compile
    name: Build and test project
    steps:
      - uses: actions/checkout@v3

      - name: Set JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '21'
          java-package: jdk
          cache: 'maven'
      
      - name: Test project
        run: mvn -f ./Test/pom.xml -B test

      - name: Echo positive result
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: 'Все тесты прошли провеку'    
      
      - name: Report
        if: always()
        uses: scacap/action-surefire-report@v1
      
      
  filter_negative_result:
    runs-on: ubuntu-latest
    if: failure()
    needs: build
    name: Send negative result if failed
    steps:
      - name: send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: "Некоторые тесты не прошли проверку. Зайдите в гитхаб для просмотра аннотации с выдержкой об ошибках"
